name: fact
channels:
  - pytorch
  - defaults
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.11.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - cpuonly=2.0
  - cryptography=41.0.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.1
  - gmpy2=2.1.2
  - icu=73.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.20.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpir=3.0.0
  - mpmath=1.3.0
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openjpeg=2.4.0
  - openssl=3.0.12
  - overrides=7.4.0
  - packaging=23.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytorch=2.1.2
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qtconsole=5.5.0
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.12
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - torchaudio=2.1.2
  - torchvision=0.16.2
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.18
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - fsspec==2023.12.2
      - ftfy==6.1.3
      - joblib==1.3.2
      - pandas==2.1.4
      - regex==2023.12.25
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - tzdata==2023.4
      - wcwidth==0.2.13
      - git+https://github.com/openai/CLIP.git
